### ISSUE TITLE
Use RelativeVirtualFile more aggressively

### ISSUE THREAD

**Issue by gzm0** [scala-js/jsdependencies#2]
Many APIs still carry metadata about the relative path of files. Since the introduction of RelativeVirtualFile we can make heavier use of it to streamline API usage.

This issue is migrated from scala-js/scala-js#2562.

**Comment by sjrd** [comment]
Not relevant anymore, since `RelativeVirtualFile` was removed in https://github.com/scala-js/scala-js/commit/585aa14f50b54211a0f684912eaa8310313f6711.
