### ISSUE TITLE
Private JSON classes

### ISSUE THREAD

**Issue by mathieuleclaire** [scala-js/jsdependencies#39]
HI,
I used to use JSONXX classes from scala-js-bundler, but I can't anymore since they are now private in jsdepencies. Would it be possible to make them public again ?
Thanks !
Mathieu

**Comment by sjrd** [comment]
No, we won't make them public. They are not part of the public API of `jsdependencies`.

Feel free to copy the source code into your own sbt plugin if you need them. They're EOL anyway, so it's not like you'll have to keep up with upstream changes. ;)

**Comment by gzm0** [comment]
FWIW: I think the only reason these are even here in the first place (rather than using a library) is that this project was born in Scala.js core, where we cannot depend on anything.

**Comment by mathieuleclaire** [comment]
OK. Thanks.
