### ISSUE TITLE
Having `JSDependenciesPlugin` enabled breaks CSS macros for Udash projects

### ISSUE THREAD

**Issue by OndrejSpanel** [scala-js/jsdependencies#51]
As seen in https://github.com/OndrejSpanel/CssRepro and its workflows, as soon as one enables `JSDependenciesPlugin`, CSS macros stop working and output of `CssRender.render` is empty. It seems having `JSDependenciesPlugin` enabled somehow breaks some macros used to process the CSS in [Udash](https://github.com/UdashFramework/udash-core).

This is true for both Udash 0.9.0 and Scala 2.13, and Udash 0.8.6 and Scala 2.12.

See Run tests section of the workflow output in:

Bad: https://github.com/OndrejSpanel/CssRepro/actions/runs/4744915939/jobs/8426488370
Good: https://github.com/OndrejSpanel/CssRepro/actions/runs/4744962509/jobs/8426598572

**Comment by sjrd** [comment]
This project was only ever meant as a transition measure for upgrading from Scala.js 0.6.x. It should not be used anymore, and we are not maintaining it. I guess fork welcome if a fix is actually required in this repo?

**Comment by OndrejSpanel** [comment]
It seems the problem is when I enable `JSDependenciesPlugin` for a JVM project. (I have also tried `ScalaJSBundlerPlugin` and it shows the same behaviour.)

One needs to use `.jsConfigure(_.enablePlugins(ScalaJSBundlerPlugin))` or `.jsConfigure(_.enablePlugins(JSDependenciesPlugin))`, not just `.enablePlugins(JSDependenciesPlugin)`.

I am not sure why this happens, but I guess those plugins were never intended to work with JVM projects.

**Comment by sjrd** [comment]
Oh, yes. You can't do that. `JSDependenciesPlugin` depends on `ScalaJSPlugin`. So if you add `JSDependenciesPlugin` to a JVM project, that makes that project not a JVM project anymore.
